<section class="mt-2">
    <div class="row">
        <div class="col-md-12">
            <div class="stripDesign">
                <div class="strip1">
                    <div class="formBox pt-2 pb-4 px-4">
                        <h6>Find products by parameters:</h6>
                        <form class="form-inline" action="{{route('search.product')}}" method="POST">
                            @csrf
                            <select class="form-control" id="group" name="group" >
                                <option value="">Motor group</option>
                                <option value="Cobra">Cobra</option>
                                <option value="Constant Velocity Fan Kit">Constant Velocity Fan Kit
                                </option>
                                <option value="Crusher Duty">Crusher Duty</option>
                                <option value="EPAct JM-JP">EPAct JM-JP</option>
                                <option value="Farm">Farm</option>
                                <option value="Farm Duty">Farm Duty</option>
                                <option value="IEC Single Phase High Torque Aluminum, TEFC">IEC
                                    Single Phase High Torque Aluminum, TEFC</option>
                                <option value="Metric IEC">Metric IEC</option>
                                <option value="Oil Pump">Oil Pump</option>
                                <option value="Phase Converter Motor">Phase Converter Motor</option>
                                <option value="PM">PM</option>
                                <option value="PM DC">PM DC</option>
                                <option value="Premium JM-JP">Premium JM-JP</option>
                                <option value="Stainless">Stainless</option>
                                <option value="Stainless Steel">Stainless Steel</option>
                                <option value="Three">Three</option>
                                <option value="Three Phase Aluminum">Three Phase Aluminum</option>
                                <option value="Three Phase Cast Iron">Three Phase Cast Iron</option>
                                <option value="Three Phase Open Enclosure">Three Phase Open
                                    Enclosure</option>
                                <option value="VFD">VFD</option>
                                <option value="Washdown">Washdown</option>
                            </select>
                            <select class="form-control" id="frame_size" name="frame_size">
                                <option value="">Frame Size</option>
                                <option value="1">1</option>
                                <option value="100L">100L</option>
                                <option value="112M">112M</option>
                                <option value="132M">132M</option>
                                <option value="132S">132S</option>
                                <option value="140T">140T</option>
                                <option value="143JM">143JM</option>
                                <option value="143JP">143JP</option>
                                <option value="143T">143T</option>
                                <option value="143TC">143TC</option>
                                <option value="145JM">145JM</option>
                                <option value="145JP">145JP</option>
                                <option value="145T">145T</option>
                                <option value="145TC">145TC</option>
                                <option value="145TD">145TD</option>
                                <option value="160L">160L</option>
                                <option value="160LB34">160LB34</option>
                                <option value="160LB35">160LB35</option>
                                <option value="160M">160M</option>
                                <option value="160MB34">160MB34</option>
                                <option value="160MB35">160MB35</option>
                                <option value="180L">180L</option>
                                <option value="180LB34">180LB34</option>
                                <option value="180LB35">180LB35</option>
                                <option value="180M">180M</option>
                                <option value="180MB34">180MB34</option>
                                <option value="180MB35">180MB35</option>
                                <option value="180T">180T</option>
                                <option value="182JM">182JM</option>
                                <option value="182JP">182JP</option>
                                <option value="182T">182T</option>
                                <option value="182TC">182TC</option>
                                <option value="184JM">184JM</option>
                                <option value="184JP">184JP</option>
                                <option value="184T">184T</option>
                                <option value="184TC">184TC</option>
                                <option value="2">2</option>
                                <option value="200L">200L</option>
                                <option value="200LB34">200LB34</option>
                                <option value="200LB35">200LB35</option>
                                <option value="210T">210T</option>
                                <option value="213JM">213JM</option>
                                <option value="213JP">213JP</option>
                                <option value="213T">213T</option>
                                <option value="213TC">213TC</option>
                                <option value="213TCZ">213TCZ</option>
                                <option value="213TZ">213TZ</option>
                                <option value="215JM">215JM</option>
                                <option value="215JP">215JP</option>
                                <option value="215T">215T</option>
                                <option value="215TC">215TC</option>
                                <option value="225M">225M</option>
                                <option value="225MB34">225MB34</option>
                                <option value="225MB35">225MB35</option>
                                <option value="225S">225S</option>
                                <option value="225SB34">225SB34</option>
                                <option value="225SB35">225SB35</option>
                                <option value="250M">250M</option>
                                <option value="250MB34">250MB34</option>
                                <option value="250MB35">250MB35</option>
                                <option value="250T">250T</option>
                                <option value="254JM">254JM</option>
                                <option value="254JP">254JP</option>
                                <option value="254T">254T</option>
                                <option value="254TC">254TC</option>
                                <option value="256JM">256JM</option>
                                <option value="256JP">256JP</option>
                                <option value="256T">256T</option>
                                <option value="256TC">256TC</option>
                                <option value="280M">280M</option>
                                <option value="280MB34">280MB34</option>
                                <option value="280MB35">280MB35</option>
                                <option value="280S">280S</option>
                                <option value="280SB34">280SB34</option>
                                <option value="280SB35">280SB35</option>
                                <option value="280T">280T</option>
                                <option value="284JM">284JM</option>
                                <option value="284JP">284JP</option>
                                <option value="284T">284T</option>
                                <option value="284TC">284TC</option>
                                <option value="284TS">284TS</option>
                                <option value="284TSC">284TSC</option>
                                <option value="286JM">286JM</option>
                                <option value="286JP">286JP</option>
                                <option value="286T">286T</option>
                                <option value="286TC">286TC</option>
                                <option value="286TS">286TS</option>
                                <option value="286TSC">286TSC</option>
                                <option value="315L">315L</option>
                                <option value="315LB34">315LB34</option>
                                <option value="315LB35">315LB35</option>
                                <option value="315S">315S</option>
                                <option value="315SB34">315SB34</option>
                                <option value="315SB35">315SB35</option>
                                <option value="320T">320T</option>
                                <option value="324JM">324JM</option>
                                <option value="324JP">324JP</option>
                                <option value="324T">324T</option>
                                <option value="324TC">324TC</option>
                                <option value="324TS">324TS</option>
                                <option value="324TSC">324TSC</option>
                                <option value="326JM">326JM</option>
                                <option value="326JP">326JP</option>
                                <option value="326T">326T</option>
                                <option value="326TC">326TC</option>
                                <option value="326TS">326TS</option>
                                <option value="326TSC">326TSC</option>
                                <option value="360T">360T</option>
                                <option value="364JM">364JM</option>
                                <option value="364JP">364JP</option>
                                <option value="364T">364T</option>
                                <option value="364TC">364TC</option>
                                <option value="364TS">364TS</option>
                                <option value="364TSC">364TSC</option>
                                <option value="365JM">365JM</option>
                                <option value="365JP">365JP</option>
                                <option value="365T">365T</option>
                                <option value="365TC">365TC</option>
                                <option value="365TS">365TS</option>
                                <option value="365TSC">365TSC</option>
                                <option value="400T">400T</option>
                                <option value="404T">404T</option>
                                <option value="404TC">404TC</option>
                                <option value="405T">405T</option>
                                <option value="405TC">405TC</option>
                                <option value="405TS">405TS</option>
                                <option value="405TSC">405TSC</option>
                                <option value="440T">440T</option>
                                <option value="444T">444T</option>
                                <option value="444TC">444TC</option>
                                <option value="444TS">444TS</option>
                                <option value="444TSC">444TSC</option>
                                <option value="445">445</option>
                                <option value="445C">445C</option>
                                <option value="445T">445T</option>
                                <option value="445TC">445TC</option>
                                <option value="445TS">445TS</option>
                                <option value="445TSC">445TSC</option>
                                <option value="447T">447T</option>
                                <option value="447TC">447TC</option>
                                <option value="447TS">447TS</option>
                                <option value="447TSC">447TSC</option>
                                <option value="449T">449T</option>
                                <option value="449TC">449TC</option>
                                <option value="449TL">449TL</option>
                                <option value="449TS">449TS</option>
                                <option value="449TSC">449TSC</option>
                                <option value="56">56</option>
                                <option value="56B34">56B34</option>
                                <option value="56B35">56B35</option>
                                <option value="56C">56C</option>
                                <option value="56H">56H</option>
                                <option value="56HC">56HC</option>
                                <option value="56HJ">56HJ</option>
                                <option value="56J">56J</option>
                                <option value="56Y">56Y</option>
                                <option value="586/7T">586/7T</option>
                                <option value="63">63</option>
                                <option value="63B14">63B14</option>
                                <option value="63B34">63B34</option>
                                <option value="63B35">63B35</option>
                                <option value="71">71</option>
                                <option value="71B34">71B34</option>
                                <option value="71B35">71B35</option>
                                <option value="80">80</option>
                                <option value="80B34">80B34</option>
                                <option value="80B35">80B35</option>
                                <option value="90">90</option>
                                <option value="90L">90L</option>
                                <option value="90S">90S</option>
                                <option value="L56HJ">L56HJ</option>
                            </select>
                            <select class="form-control" id="horsepower_60hz" name="horsepower">
                                <option value="">Horsepower</option>
                                <option value="0.12">0.12</option>
                                <option value="0.125">0.125</option>
                                <option value="0.16">0.16</option>
                                <option value="0.18">0.18</option>
                                <option value="0.25">0.25</option>
                                <option value="0.33">0.33</option>
                                <option value="0.35">0.35</option>
                                <option value="0.5">0.5</option>
                                <option value="0.75">0.75</option>
                                <option value="1">1</option>
                                <option value="1.5">1.5</option>
                                <option value="1.75">1.75</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="5.5">5.5</option>
                                <option value="7.5">7.5</option>
                                <option value="10">10</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                                <option value="25">25</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="75">75</option>
                                <option value="100">100</option>
                                <option value="125">125</option>
                                <option value="150">150</option>
                                <option value="200">200</option>
                                <option value="215">215</option>
                                <option value="250">250</option>
                                <option value="300">300</option>
                                <option value="350">350</option>
                                <option value="400">400</option>
                                <option value="450">450</option>
                                <option value="500">500</option>
                            </select>
                            <select class="form-control" id="rpm" name="rpm">
                                <option value="">Speed</option>
                                <option value="900">900</option>
                                <option value="1200">1200</option>
                                <option value="1800">1800</option>
                                <option value="3600">3600</option>
                            </select>
                            <select class="form-control" id="voltage" name="voltage">
                                <option value="">Voltage</option>
                                <option value="110">110</option>
                                <option value="115">115</option>
                                <option value="115/208-230">115/208-230</option>
                                <option value="115/230">115/230</option>
                                <option value="12">12</option>
                                <option value="180">180</option>
                                <option value="208-230">208-230</option>
                                <option value="208-230/460">208-230/460</option>
                                <option value="220">220</option>
                                <option value="230">230</option>
                                <option value="230/460">230/460</option>
                                <option value="230/460/796">230/460/796</option>
                                <option value="24">24</option>
                                <option value="460">460</option>
                                <option value="575">575</option>
                                <option value="90">90</option>
                            </select>
                            <button type="submit" class="btn btn-primary">Search</button><a class="clear-icon"><i class="far fa-times-circle" style="font-size: 1.2em;"></i></a></form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>